=== dpogue/4711Site/data/game-schedule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="schedule">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="game" type="gametype" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="gametype">
    <xs:sequence>
      <xs:element name="away" type="team" minOccurs="1" maxOccurs="1"/>
      <xs:element name="home" type="team" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="day" type="xs:unsignedInt" use="required"/>
    <xs:attribute name="month" type="month" use="required"/>
    <xs:attribute name="year" type="xs:unsignedInt" use="required"/>
    <xs:attribute name="time" type="time" use="required"/>
  </xs:complexType>

  <xs:complexType name="team" mixed="true">
    <xs:attribute name="score" type="xs:unsignedInt" use="optional"/>
  </xs:complexType>
  <xs:simpleType name="month">
    <xs:restriction base="xs:string">
      <xs:enumeration value="JAN"/>
      <xs:enumeration value="FEB"/>
      <xs:enumeration value="MAR"/>
      <xs:enumeration value="APR"/>
      <xs:enumeration value="MAY"/>
      <xs:enumeration value="JUN"/>
      <xs:enumeration value="JUL"/>
      <xs:enumeration value="AUG"/>
      <xs:enumeration value="SEP"/>
      <xs:enumeration value="OCT"/>
      <xs:enumeration value="NOV"/>
      <xs:enumeration value="DEC"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="time">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-2][0-9]:[0-5][0-9]"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== dpogue/4711Site/data/schedule-feb.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="schedule.xsl" ?>
<schedule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="game-schedule.xsd">
	<game day="1" month="FEB" year="2011" time="19:00" >
		<away score="4" >ISLANDERS</away>
		<home score="1" >THRASHERS</home>
	</game>
	<game day="2" month="FEB" year="2011" time="19:00" >
		<away score="0" >ISLANDERS</away>
		<home score="3" >PENGUINS</home>
	</game>
	<game day="5" month="FEB" year="2011" time="19:00" >
		<away score="3" >SENATORS</away>
		<home score="5" >ISLANDERS</home>
	</game>
	<game day="8" month="FEB" year="2011" time="19:00" >
		<away score="5" >MAPLE LEAFS</away>
		<home score="3" >ISLANDERS</home>
	</game>
	<game day="10" month="FEB" year="2011" time="19:30" >
		<away score="4" >ISLANDERS</away>
		<home score="3" >CANADIENS</home>
	</game>
	<game day="11" month="FEB" year="2011" time="19:00" >
		<away score="3" >PENGUINS</away>
		<home score="9" >ISLANDERS</home>
	</game>
	<game day="13" month="FEB" year="2011" time="15:00" >
		<away score="7" >ISLANDERS</away>
		<home score="6" >SABRES</home>
	</game>
	<game day="15" month="FEB" year="2011" time="19:30" >
		<away score="4" >ISLANDERS</away>
		<home score="3">SENATORS</home>
	</game>
	<game day="17" month="FEB" year="2011" time="19:00" >
		<away score="6" >BRUINS</away>
		<home score="3" >ISLANDERS</home>
	</game>
	<game day="19" month="FEB" year="2011" time="19:00" >
		<away >KINGS</away>
		<home >ISLANDERS</home>
	</game>
	<game day="21" month="FEB" year="2011" time="13:00" >
		<away >PANTHERS</away>
		<home >ISLANDERS</home>
	</game>
	<game day="22" month="FEB" year="2011" time="19:00" >
		<away >ISLANDERS</away>
		<home >MAPLE LEAFS</home>
	</game>
	<game day="24" month="FEB" year="2011" time="19:00" >
		<away >ISLANDERS</away>
		<home >FLYERS</home>
	</game>
	<game day="26" month="FEB" year="2011" time="19:00" >
		<away >CAPITALS</away>
		<home >ISLANDERS</home>
	</game>
</schedule>
